---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integration-process
  description: Servicio que expone los controles para ejecutar los procesos de integración con la BDNSAR bajo demanda.
  tags:
    - microservice
  links:
    - url: https://github.com/JCAL0199/Integrationprocess
      title: Repository
  annotations:
    backstage.io/techdocs-ref: dir:.
    endpoints/dev: https://api.dev.company1.mx/company/1/nci-bdnsarintegrationprocess
    endpoints/qa: https://api.qa.company1.mx/company/1/nci-bdnsarintegrationprocess
    endpoints/prod: https://api.company1.mx/company/1/nci-bdnsarintegrationprocess
spec:
  type: service
  owner: group:default/maria-azucena-perez
  lifecycle: production
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dispersion-ordinaria-imss
  description: Dispersión Ordinaria IMSS
  tags:
    - proceso-negocio
spec:
  type: negocio
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/integration-process
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carga-archivo
  description: Dispersión Ordinaria IMSS/Carga Archivo -Edición
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idc
  description: Dispersión Ordinaria IMSS/IDC
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
